name: pydata
channels:
  - defaults
dependencies:
  - alabaster=0.7.10=py36h174008c_0
  - appnope=0.1.0=py36hf537a9a_0
  - asn1crypto=0.24.0=py36_0
  - babel=2.5.3=py36_0
  - backcall=0.1.0=py36_0
  - bleach=2.1.3=py36_0
  - ca-certificates=2018.03.07=0
  - certifi=2018.1.18=py36_0
  - cffi=1.11.5=py36h342bebf_0
  - chardet=3.0.4=py36h96c241c_1
  - cryptography=2.2.2=py36h1de35cc_0
  - dbus=1.13.2=h760590f_1
  - decorator=4.3.0=py36_0
  - docutils=0.14=py36hbfde631_0
  - entrypoints=0.2.3=py36hd81d71f_2
  - expat=2.2.5=hb8e80ba_0
  - gettext=0.19.8.1=h15daf44_3
  - glib=2.56.1=h35bc53a_0
  - html5lib=1.0.1=py36h2f9c1c0_0
  - icu=58.2=h4b95b61_1
  - idna=2.6=py36h8628d0a_1
  - imagesize=1.0.0=py36_0
  - intel-openmp=2018.0.0=8
  - ipykernel=4.8.2=py36_0
  - ipython=6.3.1=py36_0
  - ipython_genutils=0.2.0=py36h241746c_0
  - ipywidgets=7.2.1=py36_0
  - jedi=0.12.0=py36_0
  - jinja2=2.10=py36hd36f9c5_0
  - jpeg=9b=he5867d9_2
  - jsonschema=2.6.0=py36hb385e00_0
  - jupyter=1.0.0=py36_4
  - jupyter_client=5.2.3=py36_0
  - jupyter_console=5.2.0=py36hccf5b1c_1
  - jupyter_core=4.4.0=py36h79cf704_0
  - libcxx=4.0.1=h579ed51_0
  - libcxxabi=4.0.1=hebd6815_0
  - libedit=3.1=hb4e282d_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=hdd342a3_7
  - libpng=1.6.34=he12f830_0
  - libsodium=1.0.16=h3efe00b_0
  - markupsafe=1.0=py36h3a1e703_1
  - mistune=0.8.3=py36_0
  - mkl=2018.0.2=1
  - mkl_fft=1.0.1=py36h917ab60_0
  - mkl_random=1.0.1=py36h78cc56f_0
  - nbconvert=5.3.1=py36h810822e_0
  - nbformat=4.4.0=py36h827af21_0
  - ncurses=6.0=hd04f020_2
  - notebook=5.4.1=py36_0
  - numpy=1.14.2=py36ha9ae307_1
  - numpydoc=0.8.0=py36_0
  - openssl=1.0.2o=h26aff7b_0
  - packaging=17.1=py36_0
  - pandas=0.22.0=py36h0a44026_0
  - pandoc=1.19.2.1=ha5e8f32_1
  - pandocfilters=1.4.2=py36h3b0b094_1
  - parso=0.2.0=py36_0
  - pcre=8.42=h378b8a2_0
  - pexpect=4.5.0=py36_0
  - pickleshare=0.7.4=py36hf512f8e_0
  - pip=9.0.3=py36_0
  - prompt_toolkit=1.0.15=py36haeda067_0
  - ptyprocess=0.5.2=py36he6521c3_0
  - pycparser=2.18=py36h724b2fc_1
  - pygments=2.2.0=py36h240cd3f_0
  - pyopenssl=17.5.0=py36h51e4350_0
  - pyparsing=2.2.0=py36hb281f35_0
  - pyqt=5.9.2=py36h11d3b92_0
  - pysocks=1.6.8=py36_0
  - python=3.6.5=hc167b69_0
  - python-dateutil=2.7.2=py36_0
  - pytz=2018.4=py36_0
  - pyzmq=17.0.0=py36h1de35cc_1
  - qt=5.9.5=h02808f3_0
  - qtconsole=4.3.1=py36hd96c0ff_0
  - readline=7.0=hc1231fa_4
  - requests=2.18.4=py36h4516966_1
  - send2trash=1.5.0=py36_0
  - setuptools=39.0.1=py36_0
  - simplegeneric=0.8.1=py36_2
  - sip=4.19.8=py36h0a44026_0
  - six=1.11.0=py36h0e22d5e_1
  - snowballstemmer=1.2.1=py36h6c7b616_0
  - sphinx=1.7.2=py36_0
  - sphinxcontrib=1.0=py36h9364dc8_1
  - sphinxcontrib-websupport=1.0.1=py36h92f4a7a_1
  - sqlite=3.22.0=h3efe00b_0
  - terminado=0.8.1=py36_1
  - testpath=0.3.1=py36h625a49b_0
  - tk=8.6.7=h35a86e2_3
  - tornado=5.0.1=py36_1
  - traitlets=4.3.2=py36h65bd3ce_0
  - typing=3.6.4=py36_0
  - urllib3=1.22=py36h68b9469_0
  - wcwidth=0.1.7=py36h8c6ec74_0
  - webencodings=0.5.1=py36h3b9701d_1
  - wheel=0.31.0=py36_0
  - widgetsnbextension=3.2.1=py36_0
  - xz=5.2.3=h0278029_2
  - zeromq=4.2.5=h378b8a2_0
  - zlib=1.2.11=hf3cbc9b_2
